controller_manager:
  ros__parameters:
    update_rate: 100
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    position_controller:
      type: forward_command_controller/ForwardCommandController

position_controller:
  ros__parameters:
    joints:
      - j0
      - j1
      - j2
      - j3
    
    interface_name: position
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
